routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('privacy-policy', function () {
    return view('privacy_policy');
});
Route::post('enquiryinsert','WeddingController@store')->name('enquiryinsert');
Route::post('contactus','WeddingController@contactUsStore')->name('contactus');
Route::post('venues-store','WeddingController@venueStore')->name('venues-store');
Route::get('wedding','WeddingController@index');
Route::get('services','WeddingController@services');
Route::get('contactus','WeddingController@contactUs');
Route::get('venues','WeddingController@venues')->name('venues');
Route::get('photographer','WeddingController@photographer')->name('photographer');
Route::get('makeup','WeddingController@makeup')->name('makeup');
Route::get('mehendi','WeddingController@mehendi')->name('mehendi');
Route::get('bandbaja','WeddingController@bandBaja')->name('bandbaja');
Route::get('decoration','WeddingController@decoration')->name('decoration');
Route::get('transport','WeddingController@transport')->name('transport');
Route::get('weddingplanning','WeddingController@weddingPlanning')->name('weddingplanning');
Route::get('dj','WeddingController@dj')->name('dj');
Route::get('caterers','WeddingController@caterers')->name('caterers');
Route::get('details/{slug}','WeddingController@content')->name('details');
Route::get('content','WeddingController@content')->name('content');
Route::get('dealslist/{slug}','WeddingController@dealsList')->name('dealslist');
Route::get('servicescontent/{slug}','WeddingController@servicesContent')->name('servicescontent');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
// Route::resource('index','admin\IndexController');
// Route::resource('article','admin\ArticleController');
// Route::get('exitUrl','admin\ArticleController@exitUrl');
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::group(['prefix' => 'admin','middleware' => 'auth'], function() {
    Route::resource('index','Admin\IndexController');
    Route::resource('article','Admin\ArticleController');
    Route::get('exitUrl','Admin\ArticleController@exitUrl');
    Route::get('articlestatus','Admin\ArticleController@Status');

    //images
    Route::get('images','Admin\ImageController@index');
    Route::post('images','Admin\ImageController@store')->name('images.store');
    Route::post('image-library','Admin\ImageController@store');

    //services details
    Route::resource('services','Admin\ServiceDetailsController');
    Route::get('exitservicesurl','Admin\ServiceDetailsController@exitUrl');
    Route::get('status','Admin\ServiceDetailsController@Status');
    //Deals
    Route::resource('deals','Admin\DealsController');
    Route::get('dealsUrl','Admin\DealsController@exitUrl');
    Route::get('dealsstatus','Admin\DealsController@Status');

    //Enquiries
    Route::get('enquiries','Admin\EnquiriesController@enquiries');
    Route::post('enquiries','Admin\EnquiriesController@getEnquiries')->name('getEnquiries');
});

resources/views/admin/deals-update.blade.php
<!DOCTYPE html>
<html dir="ltr" lang="en">

<head>
<meta charset = "UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords"
        content="">
    <meta name="description"
        content="">
    <meta name="robots" content="noindex,nofollow">
    <title>Big Day Celeberation</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="../../assets/images/favicon.png">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{URL::asset('assets/libs/flot/css/float-chart.css')}}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{URL::asset('dist/css/style.min.css')}}">
    <link rel="stylesheet" href="{{URL::asset('assets/extra-libs/multicheck/multicheck.css')}}">
    <link rel="stylesheet" href="{{URL::asset('assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.css')}}">
    <script src="{{URL::asset('assets/editor/ckeditor.js')}}"></script>
	<script src="{{URL::asset('assets/editor/sample.js')}}"></script>
    <style>
        .bs{
		box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1);
	    }
        .validate{
            color:red;
        }
	.form-control-01 {
		display: block;
		padding: .375rem .75rem;
		font-size: 1rem;
		line-height: 1.5;
		background-color: #f8f9fa;
		background-clip: padding-box;
		border: 1px solid #cccccc82;
		border-radius: 4px;
		border-radius: .25rem;
		transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
	}
    .id_count_active{
		background: green;
		border-radius: 50px;
		padding: 4px;
		color: #fff;
	}
	.id_count_inactive{
		background: red;
		border-radius: 50px;
		padding: 4px;
		color: #fff;
	}
	.glow {
	  color: #fff;
	  text-align: center;
	  -webkit-animation: glow 1s ease-in-out infinite alternate;
	  -moz-animation: glow 1s ease-in-out infinite alternate;
	  animation: glow 1s ease-in-out infinite alternate;
	}

	@-webkit-keyframes glow {
	  from {
		text-shadow: 0 0 10px #fff, 0 0 20px #fff, 0 0 30px green, 0 0 40px green, 0 0 50px green, 0 0 60px green, 0 0 70px green;
	  }
	  
	  to {
		text-shadow: 0 0 20px #fff, 0 0 30px green, 0 0 40px green, 0 0 50px green, 0 0 60px green, 0 0 70px green, 0 0 80px green;
	  }
	}
    </style>
</head>

<body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full"
        data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        @include('admin/header') 
        <!-- ============================================================== -->
        <!-- End Topbar header -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
         @include('admin/sidebar')
        <!-- ============================================================== -->
        <!-- End Left Sidebar - style you can find in sidebar.scss  -->
        <!-- Page wrapper  -->
        <!-- ============================================================== -->
        <div class="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title mb-0">Deals</h5>
                                @foreach($deals as $deal)
                                <form method="post" enctype="multipart/form-data" action="{{route('deals.update',$deal->DealsId)}}">
                                    {{csrf_field()}}
                                    @method('PATCH')
                                    <div class="row mt-3">
                                        <div class="col-md-4">
                                            <label>Deal</label>
                                            <input type="text" value="{{$deal->Deal}}" class="form-control" id="title" name="Title" placeholder="Enter Title">
                                            <span id="title_mobile" class="validate alert-msg"></span>
                                        </div>
                                        <div class="col-md-4">
                                            <label>Image</label>
                                            <input type="file" class="form-control" id="image" name="Image"
                                                placeholder="Enter Image" accept=".png, .jpg, .jpeg" required>
                                            <span id="image_mobile" class="validate alert-msg"></span>
                                            <span style="color:red">Image Size 411*274</span>
                                        </div>
                                        <div class="col-md-4">
                                            <label>Url</label>
                                            <input type="text" value="{{$deal->Url}}" class="form-control char_validation_add"
                                                name="Url" id="url" placeholder="Enter Url" required>
                                            <span id="url_mobile" class="validate alert-msg"></span>
                                        </div>
                                    </div>
                                    <div class="row mt-3">
                                        <div class="col-md-4">
                                            <img src="<?php echo url('./assets/images/Dealsimage') ?>/{{$deal->Image}}" width="326px"/>
                                        </div>
                                    </div>
                                    <div class="card-body d-flex justify-content-center">
                                        <button type="submit" class="btn btn-primary" id="submit">Submit</button>
                                    </div>
                                </form>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="{{URL::asset('assets/libs/jquery/dist/jquery.min.js')}}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{{URL::asset('assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{URL::asset('assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js')}}"></script>
    <script src="{{URL::asset('assets/extra-libs/sparkline/sparkline.js')}}"></script>
    <!--Wave Effects -->
    <script src="{{URL::asset('dist/js/waves.js')}}"></script>
    <!--Menu sidebar -->
    <script src="{{URL::asset('dist/js/sidebarmenu.js')}}"></script>
    <!--Custom JavaScript -->
    <script src="{{URL::asset('dist/js/custom.min.js')}}"></script>
    <!--This page JavaScript -->
    <!-- <script src="../../dist/js/pages/dashboards/dashboard1.js"></script> -->
    <script>
        var msg='{{Session::get('alert')}}';
        var exist='{{Session::has('alert')}}';
        if(exist)
        {
            alert(msg);
            }

    </script>
    <!-- Form submit -->
    <script>
        $(document).ready(function(){
            var APP_URL = {!! json_encode(url('/')) !!};
                //check url exit or not
                $("#url").keyup(function() {
                Url=$("#url").val();
                $.ajax({
                    url:APP_URL+"/admin/dealsUrl",
                    type:'get',
                    data:{Url:Url},
                    success: function (data) {
                        if(data == "Url Already Exist")
                        {
                            alert(data);
                            $('#url').val("");
                            $('#url').focus();
                        } 
                        else{

                        }
                    }
                });
            });
        });
    </script>
    <!-- Charts js Files -->
    <script src="{{URL::asset('assets/libs/flot/excanvas.js')}}"></script>
    <script src="{{URL::asset('assets/libs/flot/jquery.flot.js')}}"></script>
    <script src="{{URL::asset('assets/libs/flot/jquery.flot.pie.js')}}"></script>
    <script src="{{URL::asset('assets/libs/flot/jquery.flot.time.js')}}"></script>
    <script src="{{URL::asset('assets/libs/flot/jquery.flot.stack.js')}}"></script>
    <script src="{{URL::asset('assets/libs/flot/jquery.flot.crosshair.js')}}"></script>
    <script src="{{URL::asset('assets/libs/flot.tooltip/js/jquery.flot.tooltip.min.js')}}"></script>
    <script src="{{URL::asset('dist/js/pages/chart/chart-page-init.js')}}"></script>
    <script src="{{URL::asset('assets/extra-libs/multicheck/datatable-checkbox-init.js')}}"></script>
    <script src="{{URL::asset('assets/extra-libs/multicheck/jquery.multicheck.js')}}"></script>
    <script src="{{URL::asset('assets/extra-libs/DataTables/datatables.min.js')}}"></script>
    <script src="{{URL::asset('assets/js/change-event.js')}}"></script> 
    <script>
        /****************************************
         *       Basic Table                   *
         ****************************************/
        $('#zero_config').DataTable();
    </script>

</body>

</html>

resources/views/admin/deals.blade.php
<!DOCTYPE html>
<html dir="ltr" lang="en">

<head>
<meta charset = "UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords"
        content="">
    <meta name="description"
        content="">
    <meta name="robots" content="noindex,nofollow">
    <title>Big Day Celeberation</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="../../assets/images/favicon.png">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{URL::asset('assets/libs/flot/css/float-chart.css')}}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{URL::asset('dist/css/style.min.css')}}">
    <link rel="stylesheet" href="{{URL::asset('assets/extra-libs/multicheck/multicheck.css')}}">
    <link rel="stylesheet" href="{{URL::asset('assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.css')}}">
    <script src="{{URL::asset('assets/editor/ckeditor.js')}}"></script>
	<script src="{{URL::asset('assets/editor/sample.js')}}"></script>
    <style>
        .bs{
		box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1);
	    }
        .validate{
            color:red;
        }
	.form-control-01 {
		display: block;
		padding: .375rem .75rem;
		font-size: 1rem;
		line-height: 1.5;
		background-color: #f8f9fa;
		background-clip: padding-box;
		border: 1px solid #cccccc82;
		border-radius: 4px;
		border-radius: .25rem;
		transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
	}
    .id_count_active{
		background: green;
		border-radius: 50px;
		padding: 4px;
		color: #fff;
	}
	.id_count_inactive{
		background: red;
		border-radius: 50px;
		padding: 4px;
		color: #fff;
	}
	.glow {
	  color: #fff;
	  text-align: center;
	  -webkit-animation: glow 1s ease-in-out infinite alternate;
	  -moz-animation: glow 1s ease-in-out infinite alternate;
	  animation: glow 1s ease-in-out infinite alternate;
	}

	@-webkit-keyframes glow {
	  from {
		text-shadow: 0 0 10px #fff, 0 0 20px #fff, 0 0 30px green, 0 0 40px green, 0 0 50px green, 0 0 60px green, 0 0 70px green;
	  }
	  
	  to {
		text-shadow: 0 0 20px #fff, 0 0 30px green, 0 0 40px green, 0 0 50px green, 0 0 60px green, 0 0 70px green, 0 0 80px green;
	  }
	}
    </style>
</head>

<body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full"
        data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        @include('admin/header') 
        <!-- ============================================================== -->
        <!-- End Topbar header -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
         @include('admin/sidebar')
        <!-- ============================================================== -->
        <!-- End Left Sidebar - style you can find in sidebar.scss  -->
        <!-- Page wrapper  -->
        <!-- ============================================================== -->
        <div class="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title mb-0">Deals</h5>
                                <form method="post" enctype="multipart/form-data" action="{{route('deals.store')}}">
								    {{csrf_field()}}
                                    <div class="row mt-3">
                                        <div class="col-md-4">
                                            <label>Deal</label>
                                            <input type="text" class="form-control" id="title" name="Title" placeholder="Enter Title">
                                            <span id="title_mobile" class="validate alert-msg"></span>
                                        </div>
                                        <div class="col-md-4">
                                            <label>Image</label>
                                            <input type="file" class="form-control" id="image" name="Image"
                                                placeholder="Enter Image" accept=".png, .jpg, .jpeg" required>
                                            <span id="image_mobile" class="validate alert-msg"></span>
                                            <span style="color:red">Image Size 411*274</span>
                                        </div>
                                        <div class="col-md-4">
                                            <label>Url</label>
                                            <input type="text" class="form-control char_validation_add"
                                                name="Url" id="url" placeholder="Enter Url" required>
                                            <span id="url_mobile" class="validate alert-msg"></span>
                                        </div>
                                    </div>
                                    <div class="row">
                                    <div class="row mt-3">
                                        <div class="col-md-4">
                                            <label>Status</label>
                                            <select name="Status" class="form-control" required>
                                                <option value="1">Active</option>
                                                <option value="2">Inactive</option>
                                            </select>
                                        </div>
                                    </div>
                                    </div>
                                    <div class="card-body d-flex justify-content-center">
                                        <button type="submit" class="btn btn-primary" id="submit">Submit</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Table start -->
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Articale</h5>
                        <div class="table-responsive">
                            <table id="zero_config" class="table table-striped table-bordered" data-order='[[ 0, "desc" ]]'>
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Deal</th>
                                        <th>Url</th>
                                        <th style="width: 150px;">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($Deal as $deal)
                                    <tr>
                                        <td>
                                            @if($deal->Status == 1)
                                            <span class="id_count_active glow">{{$deal->DealsId}}</span><br>
                                            @else
                                            <span class="id_count_inactive">{{$deal->DealsId}}</span><br>
                                            @endif
                                        </td>
                                        <td>{{$deal->Deal}}</td>
                                        <td>{{$deal->Url}}</td>
                                        <td>
                                            <a href="{{route('deals.edit',$deal->DealsId)}}"><button class="btn editbtn" data-toggle="modal" data-target="#myrole"><i class="fas fa-pencil-alt"></i></button></a>
                                            <select id="pop_noti_status"  required onchange="Status(this,{{$deal->DealsId}});"  class="bs Status form-control-01"  name="Status"> 
                                                <option value="1" {{$deal->Status == 1 ? 'selected': ''}}>Active</option>
                                                <option value="0" {{$deal->Status == 0 ? 'selected': ''}}>Inactive</option>
                                            </select>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="{{URL::asset('assets/libs/jquery/dist/jquery.min.js')}}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{{URL::asset('assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{URL::asset('assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js')}}"></script>
    <script src="{{URL::asset('assets/extra-libs/sparkline/sparkline.js')}}"></script>
    <!--Wave Effects -->
    <script src="{{URL::asset('dist/js/waves.js')}}"></script>
    <!--Menu sidebar -->
    <script src="{{URL::asset('dist/js/sidebarmenu.js')}}"></script>
    <!--Custom JavaScript -->
    <script src="{{URL::asset('dist/js/custom.min.js')}}"></script>
    <!--This page JavaScript -->
    <!-- <script src="../../dist/js/pages/dashboards/dashboard1.js"></script> -->
    <script>
        var msg='{{Session::get('alert')}}';
        var exist='{{Session::has('alert')}}';
        if(exist)
        {
            alert(msg);
            }

    </script>
    <!-- Form submit -->
    <script>
        $(document).ready(function(){
            var APP_URL = {!! json_encode(url('/')) !!};
                //check url exit or not
                $("#url").keyup(function() {
                Url=$("#url").val();
                $.ajax({
                    url:APP_URL+"/admin/dealsUrl",
                    type:'get',
                    data:{Url:Url},
                    success: function (data) {
                        if(data == "Url Already Exist")
                        {
                            alert(data);
                            $('#url').val("");
                            $('#url').focus();
                        } 
                        else{

                        }
                    }
                });
            });
        });
    </script>
   <script>
         //Status Update
         var APP_URL = {!! json_encode(url('/')) !!};
         function Status(sel,Id){
                var Status= (sel.value);
                $.ajax({
                    url:APP_URL+"/admin/dealsstatus",
                    data:{Status:Status,Id:Id},
                    type: 'GET',
                    success: function (data) {
                       // console.log(data);
                        alert("Status updated successfully.");
                        window.location = 'deals';
                    }
                });
            }
    </script>
    <!-- Charts js Files -->
    <script src="{{URL::asset('assets/libs/flot/excanvas.js')}}"></script>
    <script src="{{URL::asset('assets/libs/flot/jquery.flot.js')}}"></script>
    <script src="{{URL::asset('assets/libs/flot/jquery.flot.pie.js')}}"></script>
    <script src="{{URL::asset('assets/libs/flot/jquery.flot.time.js')}}"></script>
    <script src="{{URL::asset('assets/libs/flot/jquery.flot.stack.js')}}"></script>
    <script src="{{URL::asset('assets/libs/flot/jquery.flot.crosshair.js')}}"></script>
    <script src="{{URL::asset('assets/libs/flot.tooltip/js/jquery.flot.tooltip.min.js')}}"></script>
    <script src="{{URL::asset('dist/js/pages/chart/chart-page-init.js')}}"></script>
    <script src="{{URL::asset('assets/extra-libs/multicheck/datatable-checkbox-init.js')}}"></script>
    <script src="{{URL::asset('assets/extra-libs/multicheck/jquery.multicheck.js')}}"></script>
    <script src="{{URL::asset('assets/extra-libs/DataTables/datatables.min.js')}}"></script>
    <script src="{{URL::asset('assets/js/change-event.js')}}"></script> 
    <script>
        /****************************************
         *       Basic Table                   *
         ****************************************/
        $('#zero_config').DataTable();
    </script>

</body>

</html>

resources/views/admin/sidebar.blade.php
<aside class="left-sidebar" data-sidebarbg="skin5">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav" class="pt-4">
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link"
                                href="{{url('admin/index')}}" aria-expanded="false"><i class="mdi mdi-view-dashboard"></i><span
                                    class="hide-menu">Dashboard</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" target="_blank"
                                href="{{url('admin/images')}}" aria-expanded="false"><i class="mdi mdi-view-dashboard"></i><span
                                class="hide-menu">Images</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link has-arrow waves-effect waves-dark"
                                href="javascript:void(0)" aria-expanded="false"><i class="mdi mdi-receipt"></i><span
                                    class="hide-menu">Article </span></a>
                            <ul aria-expanded="false" class="collapse  first-level">
                                <li class="sidebar-item"><a href="{{url('admin/article')}}" class="sidebar-link"><i
                                            class="mdi mdi-note-outline"></i><span class="hide-menu"> Article
                                    </span></a>
                                </li>
                            </ul>
                        </li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link"
                                href="{{url('admin/services')}}" aria-expanded="false"><i class="mdi mdi-view-dashboard"></i><span
                                class="hide-menu">Services</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link"
                                href="{{url('admin/deals')}}" aria-expanded="false"><i class="mdi mdi-view-dashboard"></i><span
                                class="hide-menu">Deals</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link"
                                href="{{url('admin/enquiries')}}" aria-expanded="false"><i class="mdi mdi-view-dashboard"></i><span
                                class="hide-menu">Enquiries</span></a>
                        </li>
                    </ul>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>